#ifndef COMMON_H
#define COMMON_H

enum E_MSG_TYPE : int {
    UNKNOWN = 0,
    LOGIN_MSG,
    LOGIN_MSG_ACK_SUCCESS,
    LOGIN_MSG_ACK_FAIL,
    REG_MSG,
    REG_MSG_ACK_SUCCESS,
    REG_MSG_ACK_FAIL,
    GET_FRIEND_INFO_REQ,
    GET_FRIEND_INFO_SUCCESS,
    GET_FRIEND_INFO_FAILED,
    ADD_FRIEND_REQ,
    ADD_FRIEND_ACK_AGREE,
    ONE_CHAT_MSG
};

#endif // COMMON_H
